name: test.general

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: calculate date
        id: envs
        run: echo "::set-output name=CURRENT_DATE::$(date -u +'%Y-%m-%dT%H-%M')"

      - name: check on different stuff
        run: |
          echo "${{steps.envs.outputs.current_date}}"
          echo "${{ github.action_path }}"
          echo "all env"
          env

      - name: show github vars
        run: |
          echo " ${{ toJson(github) }}"
